### ISSUE TITLE
error in latest release 0.1.5 Unknown error @ rest core!"

### ISSUE THREAD

**Issue by gowram** [soajs/soajs#1]
when i try to run latest release, i am getting an error message as

```
{
  "result": false,
  "errors": {
    "codes": [
      164
    ],
    "details": [
      {
        "code": 164,
        "message": "Unknown error @ rest core!"
      }
    ]
  }
}
```

it is working fine with 0.1.4. version.

**Comment by mikehajj** [comment]
Hello @gowram, can you be more specific regarding what you did?
if possible please provide step by step scenario so i can replicate the issue and help you out.

**Comment by gowram** [comment]
thanks for your support it solved.
